# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_studyrecord_aa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='recv_date',
        ),
        migrations.AddField(
            model_name='customer',
            name='bb',
            field=models.IntegerField(default=2),
        ),
    ]
