# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20171227_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyrecord',
            name='aa',
        ),
    ]
