# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_customerdistribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='数量')),
                ('weight', models.IntegerField(verbose_name='权重')),
                ('saleuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserInfo', verbose_name='销售')),
            ],
        ),
    ]
