# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-27 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_salerank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salerank',
            old_name='saleuser',
            new_name='user',
        ),
    ]
