# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-02 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_userinfo_openid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdistribution',
            name='ctime',
            field=models.DateField(verbose_name='成单时间'),
        ),
    ]
